$image = {{image}}

$primary           = {{colors.primary.default.rgba}}
$primary_fixed     = {{colors.primary_fixed.default.rgba}}
$primary_fixed_dim = {{colors.primary_fixed_dim.default.rgba}}

$border = {{colors.primary.default.rgba | set_alpha: 0.7}}
$box    = {{colors.primary.default.rgba | set_alpha: 0.1}}
$red    = {{colors.red.default.rgba}}
$green  = {{colors.green.default.rgba}}
