audio-format  = s32
alsa-resample = no
profile       = high-quality

gpu-api     = opengl
gpu-context = wayland

hwdec                 = vaapi
save-position-on-quit = yes
pause                 = yes
interpolation

osd-bar = no
border  = no

osd-font = "Google Sans Flex"
sub-font = "Google Sans Flex"
