source = ./hyprlock/colors.conf

$S = ~/.config/hypr/hyprlock/scripts

general {
  hide_cursor        = true
  ignore_empty_input = true
}

background {
  path        = $image
  blur_passes = 3
  brightness  = 0.5
}

image {
  path         = ~/.config/hypr/hyprlock/assets/EOK.jpg
  size         = 70
  border_size  = 5
  border_color = $box
  position     = 0, -340
}

input-field {
  placeholder_text  = input password
  size              = 120, 55
  position          = 0, -432
  fade_on_empty	    = false
  outline_thickness	= 1
  font_family       = Google Sans Flex Italic
  font_size         = 9
  font_color        = $primary_fixed_dim
  inner_color       = $box
  outer_color       = $border rgba(0, 0, 0, 0) $border 45deg
  fail_color        = $red rgba(0, 0, 0, 0) $red 45deg
  check_color       = $green rgba(0, 0, 0, 0) $green 45deg
}

label {
  text          = $TIME
  color         = $primary
  font_size     = 100
  font_family   = Google Sans Flex Semibold
  position      = 0, 340
  shadow_passes = 3
  shadow_size   = 10
  shadow_color  = $box
}

label {
  text      = 󰍁
  color     = $primary_fixed_dim
  font_size = 20
  position  = 0, 456
}

label {
  text        =   Hyprland
  color       = $primary_fixed
  font_size   = 10
  font_family = Google Sans Flex Italic
  position    = -895, 520
}

label {
  text        =   $LAYOUT
  color       = $primary_fixed
  font_size   = 10
  font_family = Google Sans Flex
  position    = 895, 520
}

label {
  text        = cmd[update:1000] echo "$($S/battery.sh)"
  color       = $primary_fixed
  font_size   = 10
  font_family = Google Sans Flex
  position    = 775, 520
}

label {
  text        = cmd[update:1000] echo "$(date "+%A %b %d")"
  color       = $primary
  font_size   = 17
  font_family = Google Sans Flex
  position    = 0, 253
}
