[config]
version_check = true

[config.wallpaper]
command   = "hyprctl hyprpaper wallpaper ,{{image}}"

[templates.kitty]
input_path  = './templates/kitty-colors.conf'
output_path = '../kitty/themes/matukitty.conf'
post_hook   = 'kitty +kitten themes --reload-in=all matukitty'

[templates.starship]
input_path  = './templates/starship-colors.toml'
output_path = '../starship.toml'

[templates.yazi]
input_path  = './templates/yazi-colors.toml'
output_path = '../yazi/theme.toml'

[templates.waybar]
input_path  = './templates/waybar-colors.css'
output_path = '../waybar/themes/matuwaybar.css'
post_hook   = 'systemctl --user restart waybar; pkill kded'

[templates.hyprland]
input_path  = './templates/hyprland-colors.lua'
output_path = '../hypr/hyprland/colors.lua'
post_hook   = 'hyprctl reload'

[templates.hyprlock]
input_path  = './templates/hyprlock-colors.conf'
output_path = '../hypr/hyprlock/colors.conf'

[templates.gtk3]
input_path  = './templates/gtk-colors.css'
output_path = '../gtk-3.0/matugtk.css'

[templates.gtk4]
input_path  = './templates/gtk-colors.css'
output_path = '../gtk-4.0/matugtk.css'

[templates.swaync]
input_path  = './templates/swaync-colors.css'
output_path = '../swaync/themes/matuswaync.css'
post_hook   = 'swaync-client -R -rs'

[templates.rofimain]
input_path  = './templates/rofimain-colors.rasi'
output_path = '../rofi/themes/maturofimain.rasi'

[templates.qtct]
input_path  = './templates/qtct-colors.colors'
output_path = '../../.local/share/color-schemes/MatuQTCT.colors'
post_hook   = '~/.config/matugen/scripts/matuqtct.sh'

[templates.tela]
input_path  = './templates/tela-colors.archy'
output_path = '../../.cache/matutela.archy'
post_hook   = '~/.config/matugen/scripts/matutela.sh'

#######################################################################
[templates.kdefilepicker_fix]                                         #
input_path  = '/dev/null'                                             #    
output_path = '/dev/null'                                             #
post_hook   = 'systemctl --user restart plasma-xdg-desktop-portal-kde'#
#######################################################################

[config.custom_colors]
red   = "#ff0000"
blue  = "#0000ff"
green = "#00ff00"
